[profile]
    flag="test-local"
[mongo]
    hostUri="mongodb://localhost:27017"
    name="nbaPickAndPlayTest"
[rapid]
    enabled=false
    season="2019"
    baseUrl="http://localhost:8081/games/date/"
    apiKey="nope"